# Generated by Django 2.1.8 on 2021-06-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='employe_id',
            field=models.IntegerField(blank=True, default=0, help_text='员工编号', verbose_name='工号'),
        ),
    ]
