# Generated by Django 2.1.8 on 2021-06-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userinfo_employe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.CharField(blank=True, default='ok', help_text='帐号状态', max_length=32, verbose_name='状态'),
        ),
    ]
