# Generated by Django 2.1.8 on 2021-06-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210623_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transtype',
            name='name',
            field=models.CharField(default='其他', help_text='交易分类说明', max_length=128, unique=True, verbose_name='名称'),
        ),
    ]
