# Generated by Django 2.1.8 on 2021-06-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20210623_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_user',
            field=models.CharField(max_length=32, verbose_name='支出方'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_user',
            field=models.CharField(max_length=32, verbose_name='接收方'),
        ),
    ]
