# Generated by Django 2.1.8 on 2021-06-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_employe_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='user_info',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='user_profile',
        ),
    ]
