# Generated by Django 2.1.8 on 2021-06-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_auto_20210622_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='idCard',
            new_name='id_card',
        ),
        migrations.AddField(
            model_name='employe',
            name='status',
            field=models.CharField(blank=True, default='incumbency', help_text='员工状态', max_length=32, null=True, verbose_name='状态'),
        ),
    ]
