# Generated by Django 2.1.8 on 2021-06-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_auto_20210622_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='status',
            field=models.CharField(blank=True, default='working', help_text='员工状态', max_length=32, null=True, verbose_name='状态'),
        ),
    ]
